import CardHeading from "../components/CardHeading";

const CompanyOverview = () =>{
return(
    <div>
    <CardHeading CardHeadingText ="Overview"> 
    <div className='row'>
             <div className='col-xl-12 '> 
             This document outlines BlueConnects JSON API to be used by resellers of an MVNO who uses BlueConnects as their primary OCS and provisioning software. 
             Each JSON transaction consists of a request and a response over HTTPS post. All JSON requests should be sent to https://apiatt-solutions.telgoo5.com:22712/ . 
             Method=POST Partner shall be able to send not more than 8 transactions per second, per IP. Transactions may begin to fail if the traffic exceeds above threshold.
             </div>
             
        </div>
    </CardHeading>

<CardHeading CardHeadingText ="Credentials"> 
<div className='row'>
         <div className='col-xl-12 '> 
         Each JSON transaction contains a session section. This is the information that authenticates the transaction, identifies which BlueConnects MVNO to connect to
          and which reseller of that MVNO to associate this transaction with. All of the following information can be obtained on the On-Boarding Profile, under the 
          Destination Routing tab, line 3. Clec: id: a four digit number that identifies the BlueConnects's customer. Username: a username associated with the partner
           of the MVNO Token/password: a random string generated by BlueConnects that is tied to the agent username specifically for API authentication Pin: generated 
           by BlueConnects to provide an extra level of security in the Interim APIs Agent Plan ID's: Plans created by your company for your customers.
         </div>
         
    </div>
</CardHeading>

<CardHeading CardHeadingText ="Sample Code (PHP)"> 
<div className='row'>
         <div className='col-xl-12 '> 
         Each JSON transaction contains a session section. This is the information that authenticates the transaction, identifies which BlueConnects MVNO to connect to
          and which reseller of that MVNO to associate this transaction with. All of the following information can be obtained on the On-Boarding Profile, under the 
          Destination Routing tab, line 3. Clec: id: a four digit number that identifies the BlueConnects's customer. Username: a username associated with the partner
           of the MVNO Token/password: a random string generated by BlueConnects that is tied to the agent username specifically for API authentication Pin: generated 
           by BlueConnects to provide an extra level of security in the Interim APIs Agent Plan ID's: Plans created by your company for your customers.  Each JSON transaction contains a session section. This is the information that authenticates the transaction, identifies which BlueConnects MVNO to connect to
          and which reseller of that MVNO to associate this transaction with. All of the following information can be obtained on the On-Boarding Profile, under the 
          Destination Routing tab, line 3. Clec: id: a four digit number that identifies the BlueConnects's customer. Username: a username associated with the partner
           of the MVNO Token/password: a random string generated by BlueConnects that is tied to the agent username specifically for API authentication Pin: generated 
           by BlueConnects to provide an extra level of security in the Interim APIs Agent Plan ID's: Plans created by your company for your customers.
         </div>
         
    </div>
</CardHeading>
</div>
);
};

export default CompanyOverview;